### ISSUE TITLE
All Cron expressions not valid quartz

### ISSUE THREAD

**Issue by amhudson** [boomerang-io/roadmap#252]
`0 * * * * *` is valid cron and accepted by the UI however it is not valid for the quartz scheduler

**Comment by tlawrie** [comment]
Hi @Okisa @amhudson not sure where the message is coming from but we try and refrain from using Boomerang Flow as it could be a different name when installed somewhere due to the custom name logic.

Can we just make it "Expression * * * * * is not allowed" or "Expression * * * * * is not valid" or something like that?

![image](https://user-images.githubusercontent.com/16438811/140250154-98a0f232-5063-4b69-b174-1e51ccf35c65.png)

**Comment by tlawrie** [comment]
Also @amhudson when attempting to verify the execution, I received

```
[2021-11-04 03:00:00.071] [ERROR] [    instanceName_Worker-1] [o.q.c.JobRunShell        ] : Job flow.61834b3090c0017d6f1bcd61 threw an unhandled Exception: 

java.lang.NullPointerException
	at io.boomerang.service.UserIdentityServiceImpl.getCurrentUser(UserIdentityServiceImpl.java:51)
	at io.boomerang.service.crud.WorkflowServiceImpl.getWorkflow(WorkflowServiceImpl.java:165)
	at io.boomerang.service.ExecutionServiceImpl.executeWorkflow(ExecutionServiceImpl.java:48)
	at io.boomerang.controller.ExecutionController.executeWorkflow(ExecutionController.java:27)
	at io.boomerang.quartz.FlowJob.executeInternal(FlowJob.java:57)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
	```
	
The cron expression used was `0/5 * * * *`

**Comment by amhudson** [comment]
> Hi @Okisa @amhudson not sure where the message is coming from but we try and refrain from using Boomerang Flow as it could be a different name when installed somewhere due to the custom name logic.
> 
> Can we just make it "Expression * * * * * is not allowed" or "Expression * * * * * is not valid" or something like that?
> 
> ![image](https://user-images.githubusercontent.com/16438811/140250154-98a0f232-5063-4b69-b174-1e51ccf35c65.png)

That message is from the UI. Service is returning the specific reason for invalidation that the UI can present to the user. For example:

`{ "valid":false, "cron":null, "message": "Failed to parse '0 * * * * *'. Invalid cron expression: 0 * * * * *. Both, a day-of-week AND a day-of-month parameter, are not supported."}`

**Comment by tlawrie** [comment]
Issue from the backend is now closed. Just need an updated front end message. @Okisa @LucasGrimauth
