### ISSUE TITLE
Jobs scheduled from RunScheduledJob system task fail on a NPE

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#334]
```[2022-03-28 09:00:00.012] [ERROR] [orkflowScheduler_Worker-1] [o.q.c.JobRunShell        ] : Job flow.6144265f1950a72949b00efc threw an unhandled Exception: 

java.lang.NullPointerException
	at io.boomerang.service.crud.WorkflowServiceImpl.setupTriggerDefaults(WorkflowServiceImpl.java:210)
	at io.boomerang.service.crud.WorkflowServiceImpl.getWorkflow(WorkflowServiceImpl.java:157)
	at io.boomerang.service.ExecutionServiceImpl.executeWorkflow(ExecutionServiceImpl.java:47)
	at io.boomerang.controller.ExecutionController.executeWorkflow(ExecutionController.java:27)
	at io.boomerang.quartz.WorkflowExecuteJob.executeInternal(WorkflowExecuteJob.java:75)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

[2022-03-28 09:00:00.013] [ERROR] [orkflowScheduler_Worker-1] [o.q.c.ErrorLogger        ] : Job (flow.6144265f1950a72949b00efc threw an exception.

org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at io.boomerang.service.crud.WorkflowServiceImpl.setupTriggerDefaults(WorkflowServiceImpl.java:210)
	at io.boomerang.service.crud.WorkflowServiceImpl.getWorkflow(WorkflowServiceImpl.java:157)
	at io.boomerang.service.ExecutionServiceImpl.executeWorkflow(ExecutionServiceImpl.java:47)
	at io.boomerang.controller.ExecutionController.executeWorkflow(ExecutionController.java:27)
	at io.boomerang.quartz.WorkflowExecuteJob.executeInternal(WorkflowExecuteJob.java:75)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more```

**Comment by tlawrie** [comment]
The solution ended up being to default the triggers correctly and then also fix a parameter map issue where we weren't retrieving the parameters
